import bcrypt from 'bcryptjs';
import { PersistenceService } from './persistenceService.js';
import { Category, Game, Promotion, RuntimeData, User } from '../types/index.js';

export async function seedInitialDataIfNeeded(force: boolean = false): Promise<RuntimeData> {
  const current = await PersistenceService.readData();

  // If already seeded and not forced, return
  if (!force && current.users.length > 0 && current.games.length > 0) {
    return current;
  }

  console.log('Seeding initial AMR Game Space dataset...');

  // 1. Password Hashes (Admin uses high-entropy privileged password policy)
  const adminPasswordHash = await bcrypt.hash('Admin@Sec9#Vault2026!', 10);
  const gamerPasswordHash = await bcrypt.hash('Gamer@12345', 10);

  const now = new Date().toISOString();

  // 2. Users
  const users: User[] = [
    {
      id: 'USR-10001',
      name: 'AMR Kumar',
      email: 'gamer@amrgamespace.local',
      passwordHash: gamerPasswordHash,
      role: 'customer',
      status: 'active',
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
      updatedAt: now,
      lastLoginAt: new Date(Date.now() - 3600000).toISOString(),
      phone: '+91 98765 43210',
    },
    {
      id: 'USR-10002',
      name: 'Admin Director',
      email: 'admin@amrgamespace.local',
      passwordHash: adminPasswordHash,
      role: 'admin',
      status: 'active',
      createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
      updatedAt: now,
      lastLoginAt: new Date().toISOString(),
      phone: '+91 99999 88888',
    },
    {
      id: 'USR-10003',
      name: 'Aarav Sharma',
      email: 'aarav@example.com',
      passwordHash: gamerPasswordHash,
      role: 'customer',
      status: 'active',
      createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
      updatedAt: now,
      lastLoginAt: new Date(Date.now() - 86400000).toISOString(),
      phone: '+91 91234 56789',
    },
    {
      id: 'USR-10004',
      name: 'Priya Patel',
      email: 'priya@example.com',
      passwordHash: gamerPasswordHash,
      role: 'customer',
      status: 'suspended',
      createdAt: new Date(Date.now() - 40 * 86400000).toISOString(),
      updatedAt: now,
      lastLoginAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    }
  ];

  // 3. Categories
  const categories: Category[] = [
    { id: 'CAT-10001', name: 'Action', slug: 'action', status: 'active' },
    { id: 'CAT-10002', name: 'Adventure', slug: 'adventure', status: 'active' },
    { id: 'CAT-10003', name: 'RPG', slug: 'rpg', status: 'active' },
    { id: 'CAT-10004', name: 'Shooter', slug: 'shooter', status: 'active' },
    { id: 'CAT-10005', name: 'Strategy', slug: 'strategy', status: 'active' },
    { id: 'CAT-10006', name: 'Simulation', slug: 'simulation', status: 'active' },
    { id: 'CAT-10007', name: 'Sports', slug: 'sports', status: 'active' },
    { id: 'CAT-10008', name: 'Racing', slug: 'racing', status: 'active' },
    { id: 'CAT-10009', name: 'Indie', slug: 'indie', status: 'active' },
    { id: 'CAT-10010', name: 'Multiplayer', slug: 'multiplayer', status: 'active' },
    { id: 'CAT-10011', name: 'Open World', slug: 'open-world', status: 'active' },
    { id: 'CAT-10012', name: 'Survival', slug: 'survival', status: 'active' },
  ];

  // 4. Games (18 Popular Titles)
  const games: Game[] = [
    {
      id: 'GAME-10001',
      title: 'Counter-Strike 2',
      slug: 'counter-strike-2',
      publisher: 'Valve',
      developer: 'Valve',
      description: 'The world-renowned competitive tactical multiplayer shooter built on the Source 2 engine.',
      categoryIds: ['CAT-10004', 'CAT-10010'],
      platforms: ['PC'],
      pricePaise: 0,
      originalPricePaise: 0,
      discountPercent: 0,
      rating: 4.8,
      reviewCount: 42500,
      releaseDate: '2023-09-27',
      featured: true,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10002',
      title: 'Dota 2',
      slug: 'dota-2',
      publisher: 'Valve',
      developer: 'Valve',
      description: 'Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes in competitive 5v5 action.',
      categoryIds: ['CAT-10005', 'CAT-10010'],
      platforms: ['PC'],
      pricePaise: 0,
      originalPricePaise: 0,
      discountPercent: 0,
      rating: 4.7,
      reviewCount: 38900,
      releaseDate: '2013-07-09',
      featured: false,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10003',
      title: 'PUBG: BATTLEGROUNDS',
      slug: 'pubg-battlegrounds',
      publisher: 'KRAFTON, Inc.',
      developer: 'PUBG Studios',
      description: 'Land on strategic locations, loot weapons and supplies, and survive to become the last team standing across diverse Battlegrounds.',
      categoryIds: ['CAT-10004', 'CAT-10010', 'CAT-10012'],
      platforms: ['PC'],
      pricePaise: 0,
      originalPricePaise: 0,
      discountPercent: 0,
      rating: 4.5,
      reviewCount: 29800,
      releaseDate: '2017-12-21',
      featured: false,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10004',
      title: 'Apex Legends',
      slug: 'apex-legends',
      publisher: 'Electronic Arts',
      developer: 'Respawn Entertainment',
      description: 'Conquer with character in Apex Legends, a free-to-play Hero shooter where legendary characters battle for glory and fortune.',
      categoryIds: ['CAT-10004', 'CAT-10010'],
      platforms: ['PC'],
      pricePaise: 0,
      originalPricePaise: 0,
      discountPercent: 0,
      rating: 4.6,
      reviewCount: 31200,
      releaseDate: '2019-02-04',
      featured: true,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10005',
      title: 'Marvel Rivals',
      slug: 'marvel-rivals',
      publisher: 'NetEase Games',
      developer: 'NetEase Games',
      description: 'A team-based Hero Shooter where players assemble an all-star Marvel squad to unleash superpowers in dynamic battlegrounds.',
      categoryIds: ['CAT-10004', 'CAT-10010', 'CAT-10001'],
      platforms: ['PC'],
      pricePaise: 0,
      originalPricePaise: 0,
      discountPercent: 0,
      rating: 4.7,
      reviewCount: 18400,
      releaseDate: '2024-12-06',
      featured: true,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2767030/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10006',
      title: 'Rust',
      slug: 'rust',
      publisher: 'Facepunch Studios',
      developer: 'Facepunch Studios',
      description: 'The only goal in Rust is to survive. Overcome struggles such as hunger, thirst and cold. Build a fire. Build a shelter. Kill animals. Protect yourself.',
      categoryIds: ['CAT-10012', 'CAT-10010', 'CAT-10001'],
      platforms: ['PC'],
      pricePaise: 149900,
      originalPricePaise: 149900,
      discountPercent: 0,
      rating: 4.4,
      reviewCount: 19400,
      releaseDate: '2018-02-08',
      featured: false,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10007',
      title: 'Grand Theft Auto V Enhanced',
      slug: 'grand-theft-auto-v-enhanced',
      publisher: 'Rockstar Games',
      developer: 'Rockstar North',
      description: 'Experience Los Santos and Blaine County in ultra-high resolution with ray tracing, faster load times, and dynamic world enhancements.',
      categoryIds: ['CAT-10001', 'CAT-10011', 'CAT-10002'],
      platforms: ['PC'],
      pricePaise: 124900,
      originalPricePaise: 249900,
      discountPercent: 50,
      rating: 4.9,
      reviewCount: 54000,
      releaseDate: '2015-04-14',
      featured: true,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10008',
      title: 'Stardew Valley',
      slug: 'stardew-valley',
      publisher: 'ConcernedApe',
      developer: 'ConcernedApe',
      description: 'You have inherited your grandfather\'s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, set out to begin your new life.',
      categoryIds: ['CAT-10009', 'CAT-10006', 'CAT-10003'],
      platforms: ['PC'],
      pricePaise: 47900,
      originalPricePaise: 47900,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 22000,
      releaseDate: '2016-02-26',
      featured: false,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10009',
      title: 'Baldur\'s Gate 3',
      slug: 'baldurs-gate-3',
      publisher: 'Larian Studios',
      developer: 'Larian Studios',
      description: 'Gather your party and return to the Forgotten Realms in a tale of fellowship, betrayal, sacrifice, survival, and the lure of absolute power.',
      categoryIds: ['CAT-10003', 'CAT-10005', 'CAT-10002'],
      platforms: ['PC'],
      pricePaise: 299900,
      originalPricePaise: 299900,
      discountPercent: 0,
      rating: 4.95,
      reviewCount: 48000,
      releaseDate: '2023-08-03',
      featured: true,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10010',
      title: 'Cyberpunk 2077',
      slug: 'cyberpunk-2077',
      publisher: 'CD PROJEKT RED',
      developer: 'CD PROJEKT RED',
      description: 'An open-world action-adventure RPG set in Night City, a megalopolis obsessed with power, glamour, and body modification.',
      categoryIds: ['CAT-10003', 'CAT-10001', 'CAT-10011'],
      platforms: ['PC'],
      pricePaise: 149900,
      originalPricePaise: 299900,
      discountPercent: 50,
      rating: 4.7,
      reviewCount: 36000,
      releaseDate: '2020-12-10',
      featured: true,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10011',
      title: 'Elden Ring',
      slug: 'elden-ring',
      publisher: 'FromSoftware / Bandai Namco',
      developer: 'FromSoftware',
      description: 'Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
      categoryIds: ['CAT-10003', 'CAT-10001', 'CAT-10011'],
      platforms: ['PC'],
      pricePaise: 251900,
      originalPricePaise: 359900,
      discountPercent: 30,
      rating: 4.9,
      reviewCount: 41000,
      releaseDate: '2022-02-25',
      featured: true,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10012',
      title: 'The Witcher 3: Wild Hunt',
      slug: 'the-witcher-3-wild-hunt',
      publisher: 'CD PROJEKT RED',
      developer: 'CD PROJEKT RED',
      description: 'You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will.',
      categoryIds: ['CAT-10003', 'CAT-10002', 'CAT-10011'],
      platforms: ['PC'],
      pricePaise: 49900,
      originalPricePaise: 199900,
      discountPercent: 75,
      rating: 4.9,
      reviewCount: 51000,
      releaseDate: '2015-05-18',
      featured: false,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10013',
      title: 'Red Dead Redemption 2',
      slug: 'red-dead-redemption-2',
      publisher: 'Rockstar Games',
      developer: 'Rockstar Studios',
      description: 'America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents massing, the gang must rob, steal and fight.',
      categoryIds: ['CAT-10001', 'CAT-10002', 'CAT-10011'],
      platforms: ['PC'],
      pricePaise: 105500,
      originalPricePaise: 319900,
      discountPercent: 67,
      rating: 4.9,
      reviewCount: 45000,
      releaseDate: '2019-12-05',
      featured: false,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10014',
      title: 'Forza Horizon 5',
      slug: 'forza-horizon-5',
      publisher: 'Xbox Game Studios',
      developer: 'Playground Games',
      description: 'Explore vibrant open worlds with hundreds of the world\'s greatest cars in the ultimate Horizon driving adventure.',
      categoryIds: ['CAT-10008', 'CAT-10007', 'CAT-10011'],
      platforms: ['PC'],
      pricePaise: 399900,
      originalPricePaise: 399900,
      discountPercent: 0,
      rating: 4.8,
      reviewCount: 15400,
      releaseDate: '2021-11-09',
      featured: false,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10015',
      title: 'Diablo IV',
      slug: 'diablo-iv',
      publisher: 'Blizzard Entertainment',
      developer: 'Blizzard Entertainment',
      description: 'The ultimate action RPG experience with endless evil to slaughter, countless abilities to master, nightmare dungeons, and legendary loot.',
      categoryIds: ['CAT-10003', 'CAT-10001', 'CAT-10010'],
      platforms: ['PC'],
      pricePaise: 269900,
      originalPricePaise: 449900,
      discountPercent: 40,
      rating: 4.3,
      reviewCount: 16800,
      releaseDate: '2023-06-05',
      featured: false,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/2344520/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10016',
      title: 'Hades',
      slug: 'hades',
      publisher: 'Supergiant Games',
      developer: 'Supergiant Games',
      description: 'Defy the god of the dead as you hack and slash your way out of the Underworld in this rogue-like dungeon crawler.',
      categoryIds: ['CAT-10009', 'CAT-10001', 'CAT-10003'],
      platforms: ['PC'],
      pricePaise: 110000,
      originalPricePaise: 110000,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 31000,
      releaseDate: '2020-09-17',
      featured: false,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10017',
      title: 'Hades II',
      slug: 'hades-ii',
      publisher: 'Supergiant Games',
      developer: 'Supergiant Games',
      description: 'Battle beyond the Underworld using dark sorcery to take on the Titan of Time in this bewitching rogue-like sequel.',
      categoryIds: ['CAT-10009', 'CAT-10001', 'CAT-10003'],
      platforms: ['PC'],
      pricePaise: 130000,
      originalPricePaise: 130000,
      discountPercent: 0,
      rating: 4.9,
      reviewCount: 14200,
      releaseDate: '2024-05-06',
      featured: true,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145350/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'GAME-10018',
      title: 'The Elder Scrolls V: Skyrim Special Edition',
      slug: 'the-elder-scrolls-v-skyrim-special-edition',
      publisher: 'Bethesda Softworks',
      developer: 'Bethesda Game Studios',
      description: 'Winner of more than 200 Game of the Year Awards, Skyrim Special Edition brings the epic fantasy to life with remastered art and effects.',
      categoryIds: ['CAT-10003', 'CAT-10011', 'CAT-10002'],
      platforms: ['PC'],
      pricePaise: 44900,
      originalPricePaise: 179900,
      discountPercent: 75,
      rating: 4.8,
      reviewCount: 49000,
      releaseDate: '2016-10-28',
      featured: false,
      popular: true,
      availability: 'available',
      image: 'https://cdn.cloudflare.steamstatic.com/steam/apps/489830/header.jpg',
      createdAt: now,
      updatedAt: now,
    },
  ];

  // 5. Promotions
  const promotions: Promotion[] = [
    {
      id: 'PROMO-10001',
      code: 'WELCOME10',
      type: 'percentage',
      value: 10,
      maxDiscountPaise: 100000, // max ₹1,000 off
      minimumOrderPaise: 49900, // min ₹499 order
      active: true,
      startsAt: new Date(Date.now() - 30 * 86400000).toISOString(),
      endsAt: new Date(Date.now() + 180 * 86400000).toISOString(),
      usageLimit: 500,
      usedCount: 14,
    },
    {
      id: 'PROMO-10002',
      code: 'GAMER20',
      type: 'percentage',
      value: 20,
      maxDiscountPaise: 500000, // max ₹5,000 off
      minimumOrderPaise: 100000, // min ₹1,000 order
      active: true,
      startsAt: new Date(Date.now() - 10 * 86400000).toISOString(),
      endsAt: new Date(Date.now() + 60 * 86400000).toISOString(),
      usageLimit: 100,
      usedCount: 8,
    },
    {
      id: 'PROMO-10003',
      code: 'SUMMER500',
      type: 'fixed',
      value: 50000, // ₹500 flat discount
      maxDiscountPaise: 50000,
      minimumOrderPaise: 150000, // min ₹1,500 order
      active: true,
      startsAt: new Date(Date.now() - 5 * 86400000).toISOString(),
      endsAt: new Date(Date.now() + 30 * 86400000).toISOString(),
      usageLimit: 250,
      usedCount: 22,
    }
  ];

  // 6. Demo Customer & Admin Initial Carts, Wishlists, Orders, Payments, Library
  const demoUserId = 'USR-10001';
  const adminUserId = 'USR-10002';

  const cart = {
    id: 'CART-10001',
    userId: demoUserId,
    items: [
      { gameId: 'GAME-10007', quantity: 1, addedAt: new Date(Date.now() - 3600000).toISOString() }, // GTA V
    ],
    updatedAt: now,
  };

  const adminCart = {
    id: 'CART-10002',
    userId: adminUserId,
    items: [],
    updatedAt: now,
  };

  const wishlist = {
    id: 'WISH-10001',
    userId: demoUserId,
    gameIds: ['GAME-10009', 'GAME-10011', 'GAME-10017'], // Baldur's Gate 3, Elden Ring, Hades II
    updatedAt: now,
  };

  const adminWishlist = {
    id: 'WISH-10002',
    userId: adminUserId,
    gameIds: ['GAME-10003', 'GAME-10006'], // PUBG, Rust
    updatedAt: now,
  };

  // Seed Orders for demo user and admin
  const order1Date = new Date(Date.now() - 14 * 86400000).toISOString();
  const order2Date = new Date(Date.now() - 3 * 86400000).toISOString();
  const orderAdminDate = new Date(Date.now() - 7 * 86400000).toISOString();

  const orders = [
    {
      id: 'ORD-10001',
      userId: demoUserId,
      subtotalPaise: 149900,
      discountPaise: 0,
      taxPaise: 0,
      totalPaise: 149900,
      currency: 'INR' as const,
      status: 'completed' as const,
      paymentId: 'PAY-10001',
      createdAt: order1Date,
    },
    {
      id: 'ORD-10002',
      userId: demoUserId,
      subtotalPaise: 49900,
      discountPaise: 0,
      taxPaise: 0,
      totalPaise: 49900,
      currency: 'INR' as const,
      status: 'completed' as const,
      paymentId: 'PAY-10002',
      createdAt: order2Date,
    },
    {
      id: 'ORD-10003',
      userId: adminUserId,
      subtotalPaise: 279900,
      discountPaise: 0,
      taxPaise: 0,
      totalPaise: 279900,
      currency: 'INR' as const,
      status: 'completed' as const,
      paymentId: 'PAY-10003',
      createdAt: orderAdminDate,
    },
  ];

  const orderItems = [
    {
      id: 'ITEM-10001',
      orderId: 'ORD-10001',
      gameId: 'GAME-10010', // Cyberpunk 2077
      titleSnapshot: 'Cyberpunk 2077',
      pricePaise: 149900,
      quantity: 1,
    },
    {
      id: 'ITEM-10002',
      orderId: 'ORD-10002',
      gameId: 'GAME-10012', // The Witcher 3
      titleSnapshot: 'The Witcher 3: Wild Hunt',
      pricePaise: 49900,
      quantity: 1,
    },
    {
      id: 'ITEM-10003',
      orderId: 'ORD-10003',
      gameId: 'GAME-10011', // Elden Ring
      titleSnapshot: 'Elden Ring',
      pricePaise: 279900,
      quantity: 1,
    },
  ];

  const payments = [
    {
      id: 'PAY-10001',
      orderId: 'ORD-10001',
      userId: demoUserId,
      amountPaise: 149900,
      currency: 'INR' as const,
      method: 'simulated_card' as const,
      status: 'completed' as const,
      createdAt: order1Date,
    },
    {
      id: 'PAY-10002',
      orderId: 'ORD-10002',
      userId: demoUserId,
      amountPaise: 49900,
      currency: 'INR' as const,
      method: 'simulated_upi' as const,
      status: 'completed' as const,
      createdAt: order2Date,
    },
    {
      id: 'PAY-10003',
      orderId: 'ORD-10003',
      userId: adminUserId,
      amountPaise: 279900,
      currency: 'INR' as const,
      method: 'simulated_card' as const,
      status: 'completed' as const,
      createdAt: orderAdminDate,
    },
  ];

  const library = [
    {
      id: 'LIB-10001',
      userId: demoUserId,
      gameId: 'GAME-10010', // Cyberpunk 2077
      orderId: 'ORD-10001',
      acquiredAt: order1Date,
      status: 'owned' as const,
    },
    {
      id: 'LIB-10002',
      userId: demoUserId,
      gameId: 'GAME-10012', // Witcher 3
      orderId: 'ORD-10002',
      acquiredAt: order2Date,
      status: 'owned' as const,
    },
    {
      id: 'LIB-10003',
      userId: demoUserId,
      gameId: 'GAME-10001', // Counter-Strike 2 (Free)
      orderId: 'ORD-10000',
      acquiredAt: new Date(Date.now() - 25 * 86400000).toISOString(),
      status: 'owned' as const,
    },
    {
      id: 'LIB-10004',
      userId: demoUserId,
      gameId: 'GAME-10008', // Stardew Valley
      orderId: 'ORD-10000',
      acquiredAt: new Date(Date.now() - 20 * 86400000).toISOString(),
      status: 'owned' as const,
    },
    {
      id: 'LIB-10005',
      userId: adminUserId,
      gameId: 'GAME-10011', // Elden Ring
      orderId: 'ORD-10003',
      acquiredAt: orderAdminDate,
      status: 'owned' as const,
    },
    {
      id: 'LIB-10006',
      userId: adminUserId,
      gameId: 'GAME-10010', // Cyberpunk 2077
      orderId: 'ORD-10003',
      acquiredAt: orderAdminDate,
      status: 'owned' as const,
    },
    {
      id: 'LIB-10007',
      userId: adminUserId,
      gameId: 'GAME-10001', // Counter-Strike 2
      orderId: 'ORD-10003',
      acquiredAt: orderAdminDate,
      status: 'owned' as const,
    },
    {
      id: 'LIB-10008',
      userId: adminUserId,
      gameId: 'GAME-10014', // Forza Horizon 6
      orderId: 'ORD-10003',
      acquiredAt: orderAdminDate,
      status: 'owned' as const,
    },
  ];

  // 7. Audit Logs
  const auditLogs = [
    {
      id: 'AUDIT-10001',
      userId: 'USR-10002',
      action: 'LOGIN' as const,
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      metadata: { role: 'admin', ip: '127.0.0.1' },
    },
    {
      id: 'AUDIT-10002',
      userId: demoUserId,
      action: 'ORDER_CREATED' as const,
      timestamp: order2Date,
      metadata: { orderId: 'ORD-10002', totalPaise: 49900 },
    },
    {
      id: 'AUDIT-10003',
      userId: demoUserId,
      action: 'PAYMENT_COMPLETED' as const,
      timestamp: order2Date,
      metadata: { paymentId: 'PAY-10002', method: 'simulated_upi' },
    },
    {
      id: 'AUDIT-10004',
      userId: 'USR-10002',
      action: 'PROMOTION_CREATED' as const,
      timestamp: new Date(Date.now() - 10 * 86400000).toISOString(),
      metadata: { promoCode: 'GAMER20' },
    }
  ];

  const fullData: RuntimeData = {
    users,
    games,
    categories,
    carts: [cart, adminCart],
    wishlists: [wishlist, adminWishlist],
    orders,
    orderItems,
    payments,
    library,
    promotions,
    sessions: [],
    auditLogs,
    metadata: {
      appName: 'AMR Game Space',
      version: '1.0.0',
      mode: 'simulator',
      seededAt: now,
      lastUpdated: now,
    },
  };

  await PersistenceService.writeData(fullData);
  console.log(`Successfully seeded dataset with ${users.length} users, ${games.length} games, ${categories.length} categories, ${orders.length} orders.`);
  return fullData;
}
